🌐 Added _L macro to all strings that can be localized
RigsOfRods/rigs-of-rods pull request #2645
Opened 2021-01-11 13:23 UTC by AnotherFoxGuy

2021-01-13 14:17 UTC, only-a-ptr requested changes
This is a monstercommit; most changes are OK but some ruin it.
* translated strings must not be used as `printf()` format strings. This includes `ImGui::Text()`.
* where already translated, I suggest not adding `_LC` context right now to avoid dumping old but working translations... unless Weblate can handle it.
* where not translated yet, I suggest adding `_LC` context right away.
* fixes must go to separate commits

2021-01-13 14:17 UTC, only-a-ptr commented on source/main/gui/panels/GUI_MultiplayerSelector.cpp
> +        m_serverlist_msg = _L("There are no available servers :/");
If the string wasn't localized before, add a context to it right away

2021-01-13 14:17 UTC, only-a-ptr commented on source/main/gui/panels/GUI_NodeBeamUtils.cpp
> +        ImGui::Text(_L("Yitter:   %f (%f)"),   actor->ar_nb_optimum[3] / actor->ar_num_beams, actor->ar_nb_optimum[2]);
again... the language string shouldn't contain `printf()` format specifiers.

In this instance, I suggest doing 
```
ImGui::Text(_L("%s:   %f (%f)"), _L("ValueType"),   val1, val2);
```

2021-01-13 14:17 UTC, only-a-ptr commented on tools/l10n/extract_pot.cmake
> +file(WRITE ${ror_pot} "")
this isn't "adding _L macro to all strings", it looks like some bugfix.
I'd like it to be in a separate commit

2021-01-14 08:54 UTC, only-a-ptr commented
I have an idea... let's use https://fmt.dev/latest/index.html
```
fmt::print("I'd rather be {1} than {0}.", "right", "happy");
```
@AnotherFoxGuy Would you add fmtlib to the build, replace all sprintf()s and then add the _L macros?

2021-01-14 13:26 UTC, AnotherFoxGuy commented on source/main/gui/panels/GUI_FrictionSettings.cpp
> +    this->DrawTooltip(_LC("FrictionSettings", "Drag anisotropy"), _LC("FrictionSettings", "This parameter is for making it easier(cheating) to get out from mud. To get stuck in real mud isn't fun at
The translations will be kept, but they will be marked as `Strings needing action`
The only thing translators will have to do it check if the translation is still correct and remove the `Needs editing` flag

2021-01-14 17:09 UTC, only-a-ptr approved these changes
Good work! Just address the few comments please.

2021-01-14 17:09 UTC, only-a-ptr commented on source/main/gui/panels/GUI_GameMainMenu.cpp
> +    std::string button_txt = (m_kb_focus_index == index) ? fmt::format("--> {}  <--", txt) : txt;
the caption is de-centered (1space on left, 2 on right). Otherwise, :heart: this function

2021-01-14 17:09 UTC, only-a-ptr commented on source/main/gui/panels/GUI_GamePauseMenu.cpp
> +    std::string button_txt = (m_kb_focus_index == index) ? fmt::format("--> {}  <--", txt) : txt;
ditto

2021-01-16 09:08 UTC, merged