Added overview page to doxygen doc
RigsOfRods/rigs-of-rods pull request #2659
Opened 2021-01-23 22:04 UTC by only-a-ptr

Teaser (about 20% written):
![obrazek](https://user-images.githubusercontent.com/491088/105615220-32649c80-5dcf-11eb-9081-5ee6d10f0fa5.png)

2022-02-24 02:06 UTC, Zentro commented
Is there somewhere published that this can be viewed? @only-a-ptr

2022-02-24 09:03 UTC, AnotherFoxGuy commented
> @Zentro  Is there somewhere published that this can be viewed?

Here is a preview: https://test.anotherfoxguy.com/

2022-02-24 11:26 UTC, only-a-ptr commented
@AnotherFoxGuy thanks!
@Zentro I'd like you to publish it as http://developer.rigsofrods.org/, ideally with versioning like OGRE does: /latest for latest release, /VERSION for previous releases and as an added feat, /nightly for current master branch.

2022-02-24 20:54 UTC, Zentro requested changes

2022-02-24 20:54 UTC, Zentro commented on doc/doxygen/MainPage.h
> + * > Copyright (c) 2013-2022 Thomas Fischer
Thomas is shown twice here. Should be Copyright (c) 2013-2022 Petr Ohlidal (& contributors).

2022-02-24 20:55 UTC, Zentro commented
> @AnotherFoxGuy thanks! @Zentro I'd like you to publish it as http://developer.rigsofrods.org/, ideally with versioning like [OGRE does](https://ogrecave.github.io/ogre/api/latest/): /latest for latest release, /VERSION for previous releases and as an added feat, /nightly for current master branch.

Will do.

2022-02-26 22:28 UTC, only-a-ptr commented
Guys, I need your opinions - does this make sense? https://github.com/RigsOfRods/rigs-of-rods/pull/2659/commits/cf12bafb09c8e06fb288db9832387bf9b5ed9cc8

I'm trying to document 4 different things in a single doxygen doc:
* the codebase
* angelscript API exposed by game to scripts (Script2Game)
* angelscript callbacks which the game finds and invokes in scripts (Game2Script)
* angelscript features from builtin scripts - currently it's just raceManager, but there will be more.

Is it clear what is what?

2022-02-27 04:59 UTC, tritonas00 commented
makes sense

2022-02-28 00:52 UTC, Zentro commented
Makes sense for me too.

2022-04-08 22:02 UTC, Zentro approved these changes

2022-04-08 23:33 UTC, tritonas00 approved these changes

2022-04-09 12:54 UTC, merged