Slightly modify gearbox names
RigsOfRods/rigs-of-rods pull request #2828
Opened 2021-12-02 08:44 UTC by TheDude53

Just figured it'd be nice to give the gearbox names a bit more consistency. Let me know what you guys think. Apologies in advance if I come off as a grammar nazi.

2021-12-03 21:21 UTC, only-a-ptr requested changes
Mostly OK except the first commit - remove it please.

2021-12-03 21:21 UTC, only-a-ptr commented on source/main/Application.cpp
> +const char* CONF_GEARBOX_SEMIAUTO   = "Manual shift: auto clutch";
ouch, these can't be changed - they are saved in people's config files. The reason for not using simple mnemonics is historical.

2021-12-04 19:41 UTC, TheDude53 commented
No problem.

2021-12-13 06:23 UTC, tritonas00 commented
Works fine, just make it one commit.

Are `stick` values meant for controller?

2021-12-26 21:03 UTC, only-a-ptr commented
Closing in favor of https://github.com/RigsOfRods/rigs-of-rods/pull/2839

@TheDude53 Thanks for creating this PR but no offense, the commit history is a mess. First off, you should create a separate branch with some sensible name when starting a project. Second, when asked to remove a commit, just do interactive rebase and delete it completely, revert-commits are for things which are already in upstream and rebasing isn't an option. Tip: I personally rely on http://gitextensions.github.io/ GUI, with the commandline it takes extreme concentration to figure out what's happening whereas in the GUI you just see it.

2021-12-26 21:03 UTC, closed without merging

2021-12-29 01:54 UTC, TheDude53 commented
Thanks for the tips and cleaning this thing up. Happy holidays!