Ηeadlights: ignore already attached objects
RigsOfRods/rigs-of-rods pull request #2946
Opened 2022-09-29 15:32 UTC by tritonas00

https://forum.rigsofrods.org/resources/coca-cola-t600-dry-van-trailer.86/

Load trailer, press N to open lights
Load the truck, press L to lock with the trailer and press N

```
InvalidParametersException: Object already attached to a SceneNode or a Bone in SceneNode::attachObject at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreSceneNode.cpp (line 105)
```

2022-10-03 14:38 UTC, po185021 requested changes
Add a comment `//workaround for trailer lights being already on before the truck attached` and log the exception text to console:
```
        catch (Ogre::Exception& eeh) {
            App::GetConsole()->putMessage(Console::CONSOLE_MSGTYPE_INFO, Console::CONSOLE_SYSTEM_ERROR,
                fmt::format("error toggling lights, message:{}", eeh.getFullDescription()));
        }
```
Then approved.

2022-10-03 14:50 UTC, only-a-ptr requested changes
Add a comment `//workaround for trailer lights being already on before the truck attached` and log the exception text to console:
```
        catch (Ogre::Exception& eeh) {
            App::GetConsole()->putMessage(Console::CONSOLE_MSGTYPE_INFO, Console::CONSOLE_SYSTEM_ERROR,
                fmt::format("error toggling lights, message:{}", eeh.getFullDescription()));
        }
```
Then approved.

2022-10-03 14:51 UTC, tritonas00 commented
It can be spammy though, especially with that amount of flares

![kk](https://user-images.githubusercontent.com/2660424/193607891-976ffc51-427f-4f52-888d-ee822a5aa080.png)

2022-10-03 14:56 UTC, only-a-ptr commented
> It can be spammy though, especially with that amount of flares

in that case just check `m_headlights_on` and don't call `toggleLights()` if already on. Throwing that many exceptions isn't good for FPS.

2022-10-28 11:12 UTC, only-a-ptr commented
**Purpose:** to fix a crash (unhandled exception). Apparently there's a bug in synchronizing light states between player vehicle and attached vehicles (trailers etc...).

**Estimate:** To fix correctly, wait for  #2937 to be done - it completely overhauls the light state system, and fixes this in the process. For a dirty workaround suggested by Tritonas, 1 man day should be enough.

2022-12-08 03:18 UTC, tritonas00 commented
https://github.com/RigsOfRods/rigs-of-rods/pull/2937

2022-12-08 03:18 UTC, closed without merging